name: certificate_app
description: Gorgeous Login UI

version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  font_awesome_flutter: ^8.0.1
  flutter_datetime_picker: ^1.3.5
  intl: ^0.16.1
  page_transition: ^1.1.5
  flutter_swiper: ^1.1.6
  rflutter_alert: ^1.0.3
  google_nav_bar: ^2.1.0
  qr_flutter:
    git:
      url: git://github.com/lukef/qr.flutter.git
flutter:

  uses-material-design: true

  assets:
      - assets/login_logo.png
      - assets/img/logo_yakka.png

  fonts:
    - family: WorkSansSemiBold
      fonts:
        - asset: assets/fonts/Work_Sans/WorkSans-SemiBold.ttf

    - family: WorkSansBold
      fonts:
        - asset: assets/fonts/Work_Sans/WorkSans-Bold.ttf

    - family: WorkSansMedium
      fonts:
        - asset: assets/fonts/Work_Sans/WorkSans-Medium.ttf
